/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorServiciosBDR;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;

/**
 *
 * @author chris
 */
public class Servicios extends javax.swing.JFrame {

    ControladorServiciosBDR gestorBDR = new ControladorServiciosBDR();

    String[] nomCols = {
        "id",
        "perfil",
        "nombre",
        "descripcion"
    };
    Object[][] datos;
    DefaultTableModel dtm = new DefaultTableModel(datos, nomCols);
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Servicios.class.getName());

    /**
     * Creates new form PLANTILLA_NO_USAR
     */
    public Servicios() {
        initComponents();

        jTable1.setModel(dtm);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        refrescarDatos();
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                gestorBDR.desconectar(); //se desconecta al cerrar
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TituloIngreso_Datos = new javax.swing.JLabel();
        jButtonVolverAlMenu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextPerfil = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextId = new javax.swing.JTextField();
        jButtonAñadir = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminarSelec = new javax.swing.JButton();
        jButtonEliminarTodo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonEliminarID = new javax.swing.JButton();
        jButtonImportar = new javax.swing.JButton();
        jButtonExportar = new javax.swing.JButton();
        jButtonAñadirDatosEjemplo = new javax.swing.JButton();
        jButtonVaciarCampos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextDescripcion = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonActualizarTabla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("plantilla");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TituloIngreso_Datos.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TituloIngreso_Datos.setText("SERVICIOS");

        jButtonVolverAlMenu.setText("VOLVER AL MENU");
        jButtonVolverAlMenu.addActionListener(this::jButtonVolverAlMenuActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TituloIngreso_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(jButtonVolverAlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonVolverAlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TituloIngreso_Datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("NOMBRE:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("DESCRIPCIÓN:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ID:");

        jTextNombre.addActionListener(this::jTextNombreActionPerformed);

        jTextId.setEnabled(false);

        jButtonAñadir.setText("AÑADIR");
        jButtonAñadir.addActionListener(this::jButtonAñadirActionPerformed);

        jButtonGuardar.setText("GUARDAR");

        jButtonModificar.setText("MODIFICAR");
        jButtonModificar.addActionListener(this::jButtonModificarActionPerformed);

        jButtonEliminarSelec.setText("ELIMINAR SELEC.");
        jButtonEliminarSelec.addActionListener(this::jButtonEliminarSelecActionPerformed);

        jButtonEliminarTodo.setText("ELIMINAR TODO");
        jButtonEliminarTodo.addActionListener(this::jButtonEliminarTodoActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("PERFIL:");

        jButtonEliminarID.setText("ELIMINAR POR ID");
        jButtonEliminarID.addActionListener(this::jButtonEliminarIDActionPerformed);

        jButtonImportar.setText("IMPORTAR");
        jButtonImportar.addActionListener(this::jButtonImportarActionPerformed);

        jButtonExportar.setText("EXPORTAR");
        jButtonExportar.addActionListener(this::jButtonExportarActionPerformed);

        jButtonAñadirDatosEjemplo.setText("AÑADIR DATOS DE EJEMPLO");
        jButtonAñadirDatosEjemplo.addActionListener(this::jButtonAñadirDatosEjemploActionPerformed);

        jButtonVaciarCampos.setText("VACIAR COMPOS");
        jButtonVaciarCampos.addActionListener(this::jButtonVaciarCamposActionPerformed);

        jTextDescripcion.setColumns(20);
        jTextDescripcion.setRows(5);
        jScrollPane2.setViewportView(jTextDescripcion);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(jButtonEliminarSelec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(74, 74, 74)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonEliminarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(23, 23, 23)))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(73, 73, 73)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonEliminarID, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonVaciarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAñadirDatosEjemplo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(100, 100, 100))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jButtonAñadirDatosEjemplo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonVaciarCampos)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAñadir)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonExportar))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminarTodo)
                    .addComponent(jButtonEliminarID)
                    .addComponent(jButtonEliminarSelec)
                    .addComponent(jButtonImportar))
                .addGap(19, 19, 19))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonActualizarTabla.setText("Actualizar Tabla");
        jButtonActualizarTabla.addActionListener(this::jButtonActualizarTablaActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jButtonActualizarTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonActualizarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jButtonEliminarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarTodoActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro que quieres borrar TODOS los servicios?\nEsta acción no se puede deshacer.");
        if (opcion == JOptionPane.YES_OPTION) {
            gestorBDR.borrarTodo();
            refrescarDatos();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarTodoActionPerformed

    private void jButtonEliminarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarIDActionPerformed
        String resp;

        resp = JOptionPane.showInputDialog("Inserta el id del servicio a borrar:");

        if (resp == null) {
            return;
        }

        if (resp.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "No has introducido nada.");
        } else {
            int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro que quieres borrar este servicio?\nEsta acción no se puede deshacer.");
            if (opcion == JOptionPane.YES_OPTION) {
                gestorBDR.borrarPorId(resp.trim());
            }
            refrescarDatos();
        }
    }//GEN-LAST:event_jButtonEliminarIDActionPerformed


    private void jButtonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportarActionPerformed
        Object[] opciones = {"TXT", "XML", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(
                this,
                "¿Desde qué formato quieres exportar?",
                "Seleccionar formato",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                opciones[0]
        );

        // Si pulsa Cancelar o cierra el diálogo, no hacemos nada
        if (eleccion == 2 || eleccion == JOptionPane.CLOSED_OPTION) {
            return;
        }

        javax.swing.JFileChooser selector = new javax.swing.JFileChooser();
        selector.setDialogTitle("Selecciona el fichero a exportar");

        // Filtro según el formato elegido
        if (eleccion == 0) { // TXT
            selector.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Ficheros TXT (*.txt)", "txt"));
        } else { // XML
            selector.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Ficheros XML (*.xml)", "xml"));
        }

        int resp = selector.showOpenDialog(this);
        if (resp == javax.swing.JFileChooser.APPROVE_OPTION) {
            String nombreFich = selector.getSelectedFile().getAbsolutePath();

            if (eleccion == 0) {
                gestorBDR.exportar(nombreFich + ".txt");
            } else {
                gestorBDR.exportarXML(nombreFich + ".xml");
            }

            refrescarDatos();
            JOptionPane.showMessageDialog(this, "Exportacion completada desde:\n" + nombreFich);
        }


    }//GEN-LAST:event_jButtonExportarActionPerformed

    private void jButtonAñadirDatosEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirDatosEjemploActionPerformed
        gestorBDR.añadirDatosEjemplo();
        refrescarDatos();
    }//GEN-LAST:event_jButtonAñadirDatosEjemploActionPerformed

    private void jButtonVaciarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVaciarCamposActionPerformed
        vaciarCampos();
    }//GEN-LAST:event_jButtonVaciarCamposActionPerformed

    private void jButtonVolverAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAlMenuActionPerformed
        gestorBDR.desconectar();
        Menu m = new Menu();
        m.setLocationRelativeTo(null);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVolverAlMenuActionPerformed

    private void jButtonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirActionPerformed
        String nombre, descripcion;
        String perfil;

        nombre = jTextNombre.getText();
        descripcion = jTextDescripcion.getText();

        perfil = jTextPerfil.getText().trim();

        if (perfil.isEmpty() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Los campos Perfil y Nombre son obligatorios.",
                    "Faltan datos",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            gestorBDR.añadir(perfil, nombre, descripcion);
        } catch (SQLException ex) {
            System.getLogger(Servicios.class.getName())
                    .log(System.Logger.Level.ERROR, (String) null, ex);
        }

        refrescarDatos();

    }//GEN-LAST:event_jButtonAñadirActionPerformed

    private void jButtonImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportarActionPerformed
        Object[] opciones = {"TXT", "XML", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(
                this,
                "¿Desde qué formato quieres importar?",
                "Seleccionar formato",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                opciones[0]
        );

        // Si pulsa Cancelar o cierra el diálogo, no hacemos nada
        if (eleccion == 2 || eleccion == JOptionPane.CLOSED_OPTION) {
            return;
        }

        javax.swing.JFileChooser selector = new javax.swing.JFileChooser();
        selector.setDialogTitle("Selecciona el fichero a importar");

        // Filtro según el formato elegido
        if (eleccion == 0) { // TXT
            selector.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Ficheros TXT (*.txt)", "txt"));
        } else { // XML
            selector.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Ficheros XML (*.xml)", "xml"));
        }

        int resp = selector.showOpenDialog(this);
        if (resp == javax.swing.JFileChooser.APPROVE_OPTION) {
            String nombreFich = selector.getSelectedFile().getAbsolutePath();

            if (eleccion == 0) {
                gestorBDR.importarTXT(nombreFich);
            } else {
                gestorBDR.importarXML(nombreFich);
            }

            refrescarDatos();
            JOptionPane.showMessageDialog(this, "Importación completada desde:\n" + nombreFich);
        }

    }//GEN-LAST:event_jButtonImportarActionPerformed
    private void vaciarCampos() {
        jTextId.setText("");
        jTextPerfil.setText("");
        jTextNombre.setText("");
        jTextDescripcion.setText("");
    }
    private void refrescarDatos() {
        datos = gestorBDR.obtenerMatriz();
        dtm.setDataVector(datos, nomCols);
        jTable1.getColumn("id").setPreferredWidth(60);
        jTable1.getColumn("perfil").setPreferredWidth(140);
        jTable1.getColumn("nombre").setPreferredWidth(220);
        jTable1.getColumn("descripcion").setPreferredWidth(380);
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String perfil, nombre, descripcion;
        int filaSelec, id;
        filaSelec = jTable1.getSelectedRow();
        System.out.println("Fila seleccionada: " + jTable1.getSelectedRow());
        id = (int) datos[filaSelec][0];
        perfil = (String) datos[filaSelec][1];
        nombre = (String) datos[filaSelec][2];
        descripcion = (String) datos[filaSelec][3];
        jTextId.setText(id + "");
        jTextPerfil.setText(perfil);
        jTextNombre.setText(nombre);
        jTextDescripcion.setText(descripcion);
        System.out.println("id=" + id + " perfil=" + perfil);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonActualizarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarTablaActionPerformed
        refrescarDatos();
    }//GEN-LAST:event_jButtonActualizarTablaActionPerformed

    private void jButtonEliminarSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarSelecActionPerformed
        int filaSelec = jTable1.getSelectedRow();
        if (filaSelec != -1) {
            gestorBDR.borrarSelec(filaSelec);
            refrescarDatos();
        }
    }//GEN-LAST:event_jButtonEliminarSelecActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        String id, nombre, descripcion;
        String perfil;
        
        id = jTextId.getText();
        nombre = jTextNombre.getText();
        descripcion = jTextDescripcion.getText();
        
        perfil = jTextPerfil.getText().trim();
        
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Selecciona un servicio de la tabla para modificarlo.",
                    "Faltan datos",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (perfil.isEmpty() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Los campos Perfil y Nombre son obligatorios.",
                    "Faltan datos",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        try {
            gestorBDR.modificar(id, perfil, nombre, descripcion);
        } catch (SQLException ex) {
            System.getLogger(Servicios.class.getName())
                    .log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        refrescarDatos();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Servicios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloIngreso_Datos;
    private javax.swing.JButton jButtonActualizarTabla;
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonAñadirDatosEjemplo;
    private javax.swing.JButton jButtonEliminarID;
    private javax.swing.JButton jButtonEliminarSelec;
    private javax.swing.JButton jButtonEliminarTodo;
    private javax.swing.JButton jButtonExportar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonImportar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonVaciarCampos;
    private javax.swing.JButton jButtonVolverAlMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextDescripcion;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextPerfil;
    // End of variables declaration//GEN-END:variables
}
