/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorValoracionesBDR;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chris
 */
public class Valoraciones extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger
            = java.util.logging.Logger.getLogger(Valoraciones.class.getName());

    String[] nomCols = {"ID", "Particular", "Profesional", "Puntuacion", "Comentario", "Fecha"};
    Object[][] datos;
    DefaultTableModel dtm = new DefaultTableModel(datos, nomCols);
    ControladorValoracionesBDR gestorValoraciones = new ControladorValoracionesBDR();

    /**
     * Creates new form PLANTILLA_NO_USAR
     */
    public Valoraciones() {
        initComponents();
        jTable.setModel(dtm);
        jTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable.getColumn("ID").setPreferredWidth(40);
        jTable.getColumn("Particular").setPreferredWidth(130);
        jTable.getColumn("Profesional").setPreferredWidth(160);
        jTable.getColumn("Puntuacion").setPreferredWidth(70);
        jTable.getColumn("Comentario").setPreferredWidth(230);
        jTable.getColumn("Fecha").setPreferredWidth(90);

        jLabelProfesional.setText("PARTICULAR:");
        jLabel6.setText("PROFESIONAL:");
        jLabel4.setText("FECHA (dd-MM-yyyy):");

        cargarCombos();
        refrescarDatos();
    }

    private void cargarCombos() {
        //PARTICULAR
        String[] particulares = gestorValoraciones.obtenerParticulares();
        jComboBoxParticular.removeAllItems();
        for (String p : particulares) {
            jComboBoxParticular.addItem(p);
        }
        //PROFESIONAL
        String[] profesionales = gestorValoraciones.obtenerProfesionales();
        jComboBoxProfesional.removeAllItems();
        for (String p : profesionales) {
            jComboBoxProfesional.addItem(p);
        }
    }

    private void refrescarDatos() {
        datos = gestorValoraciones.obtenerMatriz();
        dtm.setDataVector(datos, nomCols);
    }

    private void vaciarCampos() {
        jTextFieldID.setText("");
        jComboBoxParticular.setSelectedIndex(0);
        jComboBoxProfesional.setSelectedIndex(0);
        jComboBoxPuntuacion.setSelectedIndex(0);
        jTextAreaComentario.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }

    private int extraerId(String textoCombo) {
        return Integer.parseInt(textoCombo.split(" - ")[0].trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TituloIngreso_Datos = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButtonNuevo = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminarTodo = new javax.swing.JButton();
        jButtonEliminarPorId = new javax.swing.JButton();
        jLabelProfesional = new javax.swing.JLabel();
        jButtonEliminarSelec = new javax.swing.JButton();
        jComboBoxParticular = new javax.swing.JComboBox<>();
        jComboBoxPuntuacion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaComentario = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jComboBoxProfesional = new javax.swing.JComboBox<>();
        jLabelRol1 = new javax.swing.JLabel();
        jButtonExportar = new javax.swing.JButton();
        jButtonImportar = new javax.swing.JButton();
        jButtonVaciarCampos = new javax.swing.JButton();
        jButtonAñadirDatosEjemplo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButtonActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Valoraciones");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TituloIngreso_Datos.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TituloIngreso_Datos.setText("INGRESO DE DATOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(TituloIngreso_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(TituloIngreso_Datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("PUNTUACION:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("FECHA:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("COMENTARIO:");

        jTextFieldID.setEditable(false);
        jTextFieldID.addActionListener(this::jTextFieldIDActionPerformed);

        jTextField4.addActionListener(this::jTextField4ActionPerformed);

        jButtonNuevo.setText("NUEVO");
        jButtonNuevo.addActionListener(this::jButtonNuevoActionPerformed);

        jButtonGuardar.setText("GUARDAR");
        jButtonGuardar.addActionListener(this::jButtonGuardarActionPerformed);

        jButtonModificar.setText("MODIFICAR");
        jButtonModificar.addActionListener(this::jButtonModificarActionPerformed);

        jButtonEliminarTodo.setText("ELIMINAR TODO");
        jButtonEliminarTodo.addActionListener(this::jButtonEliminarTodoActionPerformed);

        jButtonEliminarPorId.setText("ELIMINAR POR ID");
        jButtonEliminarPorId.addActionListener(this::jButtonEliminarPorIdActionPerformed);

        jLabelProfesional.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelProfesional.setText("PROFESIONAL:");

        jButtonEliminarSelec.setText("ELIMINAR SELEC.");
        jButtonEliminarSelec.addActionListener(this::jButtonEliminarSelecActionPerformed);

        jComboBoxParticular.addActionListener(this::jComboBoxParticularActionPerformed);

        jComboBoxPuntuacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1", "2", "3", "4", "5" }));
        jComboBoxPuntuacion.addActionListener(this::jComboBoxPuntuacionActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("ID:");

        jTextAreaComentario.setColumns(20);
        jTextAreaComentario.setRows(5);
        jScrollPane2.setViewportView(jTextAreaComentario);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("NOMBRE:");

        jTextField5.addActionListener(this::jTextField5ActionPerformed);

        jLabelRol1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRol1.setText("PARTICULAR:");

        jButtonExportar.setText("EXPORTAR");
        jButtonExportar.addActionListener(this::jButtonExportarActionPerformed);

        jButtonImportar.setText("IMPORTAR");
        jButtonImportar.addActionListener(this::jButtonImportarActionPerformed);

        jButtonVaciarCampos.setText("VACIAR COMPOS");
        jButtonVaciarCampos.addActionListener(this::jButtonVaciarCamposActionPerformed);

        jButtonAñadirDatosEjemplo.setText("AÑADIR DATOS DE EJEMPLO");
        jButtonAñadirDatosEjemplo.addActionListener(this::jButtonAñadirDatosEjemploActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabelProfesional)
                            .addComponent(jLabelRol1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxParticular, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(jTextFieldID))
                                .addGap(40, 40, 40)
                                .addComponent(jLabel1))
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonVaciarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAñadirDatosEjemplo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEliminarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButtonEliminarPorId, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEliminarSelec, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelProfesional))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxParticular, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRol1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonVaciarCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAñadirDatosEjemplo))
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonExportar))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminarPorId)
                    .addComponent(jButtonEliminarTodo)
                    .addComponent(jButtonEliminarSelec)
                    .addComponent(jButtonImportar))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane.setViewportView(jTable);

        jButtonActualizar.setText("ACTUALIZAR");
        jButtonActualizar.addActionListener(this::jButtonActualizarActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane)
                    .addComponent(jButtonActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {
        int filaSelec = jTable.getSelectedRow();
        System.out.println("Fila seleccionada: " + filaSelec);

        jTextFieldID.setText(datos[filaSelec][0].toString());

        String nombrePart = (String) datos[filaSelec][1];
        for (int i = 0; i < jComboBoxParticular.getItemCount(); i++) {
            if (jComboBoxParticular.getItemAt(i).contains(nombrePart)) {
                jComboBoxParticular.setSelectedIndex(i);
                break;
            }
        }

        String nombreProf = (String) datos[filaSelec][2];
        for (int i = 0; i < jComboBoxProfesional.getItemCount(); i++) {
            if (jComboBoxProfesional.getItemAt(i).contains(nombreProf)) {
                jComboBoxProfesional.setSelectedIndex(i);
                break;
            }
        }

        jComboBoxPuntuacion.setSelectedItem(datos[filaSelec][3].toString());
        jTextAreaComentario.setText(datos[filaSelec][4] != null
                ? datos[filaSelec][4].toString() : "");
        jTextField4.setText((String) datos[filaSelec][5]);
    }

    private void jButtonEliminarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarTodoActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(rootPane,
                "¿Seguro que quieres eliminar TODAS las valoraciones?\nEsta accion no se puede deshacer.",
                "Confirmar eliminar todo", JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (respuesta == JOptionPane.YES_OPTION) {
            for (int i = dtm.getRowCount() - 1; i >= 0; i--) {
                int id = (int) datos[i][0];
                gestorValoraciones.eliminar(id);
            }
            refrescarDatos();
            vaciarCampos();
        }
    }//GEN-LAST:event_jButtonEliminarTodoActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jComboBoxParticularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxParticularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxParticularActionPerformed

    private void jComboBoxPuntuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPuntuacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPuntuacionActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        if (jTextFieldID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,
                    "Selecciona primero una valoracion de la tabla.");
        } else {
            int id = Integer.parseInt(jTextFieldID.getText());
            int idPart = extraerId(jComboBoxParticular.getSelectedItem().toString());
            int idProf = extraerId(jComboBoxParticular.getSelectedItem().toString());
            String fecha = jTextField4.getText().trim();
            int puntuacion = Integer.parseInt(jComboBoxPuntuacion.getSelectedItem().toString());
            String comentario = jTextAreaComentario.getText().trim();

            if (idPart == idProf) {
                JOptionPane.showMessageDialog(rootPane,
                        "El particular y el profesional no pueden ser la misma persona.");
            } else if (!fecha.matches("\\d{2}-\\d{2}-\\d{4}")) {
                JOptionPane.showMessageDialog(rootPane,
                        "Formato de fecha incorrecto. Usa dd-MM-yyyy  (ej: 23-04-2026)");
            } else {
                gestorValoraciones.modificar(id, idPart, idProf, puntuacion, comentario, fecha);
                refrescarDatos();
                vaciarCampos();
                JOptionPane.showMessageDialog(rootPane, "Valoracion modificada correctamente.");
            }
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminarSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarSelecActionPerformed
        int filaSelec = jTable.getSelectedRow();

        if (filaSelec < 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "Selecciona primero una valoracion de la tabla.");
        } else {
            int id = (int) datos[filaSelec][0];
            int respuesta = JOptionPane.showConfirmDialog(rootPane,
                    "¿Seguro que quieres eliminar la valoracion con ID " + id + "?",
                    "Confirmar eliminacion", JOptionPane.YES_NO_OPTION);

            if (respuesta == JOptionPane.YES_OPTION) {
                gestorValoraciones.eliminar(id);
                refrescarDatos();
                vaciarCampos();
            }
        }
    }//GEN-LAST:event_jButtonEliminarSelecActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        int idPart = extraerId(jComboBoxParticular.getSelectedItem().toString());
        int idProf = extraerId(jComboBoxParticular.getSelectedItem().toString());
        String fecha = jTextField4.getText().trim();
        int puntuacion = Integer.parseInt(jComboBoxPuntuacion.getSelectedItem().toString());
        String comentario = jTextAreaComentario.getText().trim();

        if (idPart == idProf) {
            JOptionPane.showMessageDialog(rootPane,
                    "El particular y el profesional no pueden ser la misma persona.");
        } else if (!fecha.matches("\\d{2}-\\d{2}-\\d{4}")) {
            JOptionPane.showMessageDialog(rootPane,
                    "Formato de fecha incorrecto. Usa dd-MM-yyyy  (ej: 23-04-2026)");
        } else {
            gestorValoraciones.insertar(idPart, idProf, puntuacion, comentario, fecha);
            refrescarDatos();
            vaciarCampos();
            JOptionPane.showMessageDialog(rootPane, "Valoracion guardada correctamente.");
        }    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonEliminarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPorIdActionPerformed
        String respuesta = JOptionPane.showInputDialog("Introduce el ID de la valoracion a eliminar:");

        if (respuesta == null || respuesta.isBlank()) {
            JOptionPane.showMessageDialog(rootPane,
                    "No se ha introducido ningun ID valido.");
        } else {
            int id = Integer.parseInt(respuesta);
            int confirmacion = JOptionPane.showConfirmDialog(rootPane,
                    "¿Seguro que quieres eliminar la valoracion con ID " + id + "?",
                    "Confirmar eliminacion", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                gestorValoraciones.eliminar(id);
                refrescarDatos();
                vaciarCampos();
            }
        }
    }//GEN-LAST:event_jButtonEliminarPorIdActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        vaciarCampos();
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        refrescarDatos();
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonAñadirDatosEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirDatosEjemploActionPerformed
        gestorValoraciones.generarDatosDeEjemplo();

        refrescarDatos();

        JOptionPane.showMessageDialog(rootPane, "4 datos de ejemplo han sido añadidos correctamente.");
    }//GEN-LAST:event_jButtonAñadirDatosEjemploActionPerformed

    private void jButtonVaciarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVaciarCamposActionPerformed
        vaciarCampos();
    }//GEN-LAST:event_jButtonVaciarCamposActionPerformed

    private void jButtonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportarActionPerformed
        Object[] opciones = {".txt", ".xml"};
        int formato = JOptionPane.showOptionDialog(rootPane,
                "¿En qué formato quieres exportar?",
                "Seleccionar formato",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, opciones, opciones[0]);

        if (formato == JOptionPane.CLOSED_OPTION) {
            return;
        }

        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
        fc.setDialogTitle("Guardar valoraciones");
        fc.setSelectedFile(new java.io.File(
                formato == 0 ? "valoraciones.txt" : "valoraciones.xml"));

        if (fc.showSaveDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivo = fc.getSelectedFile();
            if (formato == 0) {
                gestorValoraciones.exportarTxt(archivo, datos);
            } else {
                gestorValoraciones.exportarXml(archivo, datos);
            }
            JOptionPane.showMessageDialog(rootPane,
                    "Exportacion completada:\n" + archivo.getAbsolutePath());
        }
    }//GEN-LAST:event_jButtonExportarActionPerformed

    private void jButtonImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportarActionPerformed
            Object[] opciones = {".txt", ".xml"};
    int formato = JOptionPane.showOptionDialog(rootPane,
            "¿Desde qué formato quieres importar?",
            "Seleccionar formato",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null, opciones, opciones[0]);

    if (formato == JOptionPane.CLOSED_OPTION) {
        return;
    }

    javax.swing.JFileChooser fc = new javax.swing.JFileChooser();
    fc.setDialogTitle("Abrir archivo de valoraciones");

    if (fc.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File archivo = fc.getSelectedFile();
        int[] resultado;

        if (formato == 0) {
            resultado = gestorValoraciones.importarTxt(archivo);
        } else {
            resultado = gestorValoraciones.importarXml(archivo);
        }

        refrescarDatos();
        JOptionPane.showMessageDialog(rootPane,
                "Importacion completada.\n" +
                "Insertados: " + resultado[0] + "\n" +
                "Errores: "    + resultado[1]);
    }
    }//GEN-LAST:event_jButtonImportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Valoraciones().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloIngreso_Datos;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonAñadirDatosEjemplo;
    private javax.swing.JButton jButtonEliminarPorId;
    private javax.swing.JButton jButtonEliminarSelec;
    private javax.swing.JButton jButtonEliminarTodo;
    private javax.swing.JButton jButtonExportar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonImportar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonVaciarCampos;
    private javax.swing.JComboBox<String> jComboBoxParticular;
    private javax.swing.JComboBox<String> jComboBoxProfesional;
    private javax.swing.JComboBox<String> jComboBoxPuntuacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelProfesional;
    private javax.swing.JLabel jLabelRol1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextArea jTextAreaComentario;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables
}
